export const GET_MORE_COMMENTS_REQUEST = 'GET_MORE_COMMENTS_REQUEST';
export const GET_MORE_COMMENTS_SUCCESS = 'GET_MORE_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';

export const GET_PAGE_COMMENTS_REQUEST = 'GET_PAGE_COMMENTS_REQUEST';
export const GET_PAGE_COMMENTS_SUCCESS = 'GET_PAGE_COMMENTS_SUCCESS';


export const CHANGE_INPUT_NAME = 'CHANGE_INPUT_NAME';
export const CHANGE_INPUT_TEXT =  'CHANGE_INPUT_TEXT';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';