export const CHANGE_INPUT_NAME = 'CHANGE_INPUT_NAME';
export const CHANGE_INPUT_TEXT =  'CHANGE_INPUT_TEXT';
export const ADD_COMMENT_BTN_CLICK = 'ADD_COMMENT_BTN_CLICK';


export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';


export const GET_MORE_COMMENTS_REQUEST = 'GET_MORE_COMMENTS_REQUEST';
export const GET_MORE_COMMENTS_SUCCESS = 'GET_MORE_COMMENTS_SUCCESS';
export const GET_MORE_COMMENTS_FAIL = ' GET_MORE_COMMENTS_FAIL';
